
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Due to reverse proxy have to give this IP address
http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.89.254

homeassistant:
  packages: !include_dir_named include

python_script:

# Add custom lovelace frontend
lovelace:
  mode: storage
  dashboards:
    # Main Dashboard
    ui-dashboard:
      require_admin: false
      show_in_sidebar: true
      icon: mdi:gauge
      title: Dashboard
      filename: common/ui/ui-lovelace.yaml
      mode: yaml
