
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Due to reverse proxy have to give this IP address
http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.89.254

# Add custom lovelace frontend
lovelace:
  mode: yaml
  resources:
    - url: /www/community/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:home
      show_in_sidebar: true
      filename: ui/lovelace.yaml

homeassistant:
  packages: !include_dir_named include