title: Environment
path: environment

type: custom:grid-layout
layout: !include ../layouts/view-page-margin.yaml

cards:
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout: !include ../layouts/view-page-main-item-columns.yaml
    view_layout:
      grid-area: cc
    cards:
      - !include environment/summary.yaml
      - !include environment/temperature.yaml
      - !include environment/humidity.yaml